# Generated by Django 2.2.5 on 2020-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_desc_01', models.CharField(max_length=3000)),
                ('news_desc_02', models.CharField(max_length=3000)),
                ('news_desc_03', models.CharField(max_length=3000)),
                ('news_pic_nam', models.CharField(max_length=255)),
                ('rdate', models.CharField(max_length=10)),
                ('nom_ratio_01', models.CharField(max_length=10)),
                ('bor_ratio_01', models.CharField(max_length=10)),
                ('etc_ratio_01', models.CharField(max_length=10)),
                ('nom_ratio_02', models.CharField(max_length=10)),
                ('bor_ratio_02', models.CharField(max_length=10)),
                ('etc_ratio_02', models.CharField(max_length=10)),
                ('nom_ratio_03', models.CharField(max_length=10)),
                ('bor_ratio_03', models.CharField(max_length=10)),
                ('etc_ratio_03', models.CharField(max_length=10)),
                ('nom_ratio_04', models.CharField(max_length=10)),
                ('bor_ratio_04', models.CharField(max_length=10)),
                ('etc_ratio_04', models.CharField(max_length=10)),
                ('nom_ratio_05', models.CharField(max_length=10)),
                ('bor_ratio_05', models.CharField(max_length=10)),
                ('etc_ratio_05', models.CharField(max_length=10)),
                ('nom_ratio_06', models.CharField(max_length=10)),
                ('bor_ratio_06', models.CharField(max_length=10)),
                ('etc_ratio_06', models.CharField(max_length=10)),
                ('nom_ratio_07', models.CharField(max_length=10)),
                ('bor_ratio_07', models.CharField(max_length=10)),
                ('etc_ratio_07', models.CharField(max_length=10)),
                ('nom_ratio_08', models.CharField(max_length=10)),
                ('bor_ratio_08', models.CharField(max_length=10)),
                ('etc_ratio_08', models.CharField(max_length=10)),
                ('nom_ratio_09', models.CharField(max_length=10)),
                ('bor_ratio_09', models.CharField(max_length=10)),
                ('etc_ratio_09', models.CharField(max_length=10)),
                ('nom_ratio_10', models.CharField(max_length=10)),
                ('bor_ratio_10', models.CharField(max_length=10)),
                ('etc_ratio_10', models.CharField(max_length=10)),
                ('nom_ratio_11', models.CharField(max_length=10)),
                ('bor_ratio_11', models.CharField(max_length=10)),
                ('etc_ratio_11', models.CharField(max_length=10)),
                ('nom_ratio_12', models.CharField(max_length=10)),
                ('bor_ratio_12', models.CharField(max_length=10)),
                ('etc_ratio_12', models.CharField(max_length=10)),
            ],
        ),
    ]
