# Generated by Django 2.2.5 on 2020-11-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='news_desc_01',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
