# Generated by Django 2.2.5 on 2020-11-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201127_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rdate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
